/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package punchcardrecords.ui;

import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import punchcardrecords.common.PropertyUtils;

/**
 *
 * @author Administrator
 */
public class Abort extends javax.swing.JFrame {

    /**
     * Creates new form Abort
     * @param mainFrame
     */
    public Abort(JFrame mainFrame) {
        initComponents();
        init(mainFrame);
    }
    
    private void init(JFrame mainFrame){
        this.setTitle("关于信息");
        softName.setText(PropertyUtils.instanceVersion().getName());
        version.setText(PropertyUtils.instanceVersion().getVersion());
        name.setText(PropertyUtils.instanceVersion().getName());
        update.setText(PropertyUtils.instanceVersion().getTime());
        try {
            // 设置窗体图标
            Image logo = ImageIO.read(this.getClass().getResource("/resources/image/logo.png"));
            if(null != logo){
                this.setIconImage(logo);
            }
        } catch (IOException ex) {
            Logger.getLogger(PunchCardRecordsMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         // 设置窗体在屏幕中间显示
        this.setLocationRelativeTo(mainFrame);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        softName = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        developer = new javax.swing.JLabel();
        versionTitle = new javax.swing.JLabel();
        toUse = new javax.swing.JLabel();
        versionTime = new javax.swing.JLabel();
        devloperName = new javax.swing.JLabel();
        toUser = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        softNameTitle = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        softName.setFont(new java.awt.Font("华文隶书", 1, 14)); // NOI18N
        softName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        softName.setText("智汇方象(青岛)考勤统计软件");

        subTitle.setFont(new java.awt.Font("华文隶书", 0, 12)); // NOI18N
        subTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle.setText("版权信息");

        developer.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        developer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        developer.setText("制作人：");

        versionTitle.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        versionTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionTitle.setText("版本号：");

        toUse.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        toUse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        toUse.setText("授权人：");

        versionTime.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        versionTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionTime.setText("版本时间：");

        devloperName.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        devloperName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        devloperName.setText("JavaBird域名拥有者@仇宇");

        toUser.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        toUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        toUser.setText("智汇方象@孙荣荣");

        version.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        version.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        version.setText("1.2.8");

        update.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        update.setText("2016-1-14 15:13:12");

        softNameTitle.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        softNameTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        softNameTitle.setText("软件名称：");

        name.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setText("智汇方象(青岛)考勤统计软件");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(softName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toUse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(versionTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(versionTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(developer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(softNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(devloperName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(version, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(softName)
                .addGap(0, 0, 0)
                .addComponent(subTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(softNameTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(developer)
                    .addComponent(devloperName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toUse)
                    .addComponent(toUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionTime)
                    .addComponent(update))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developer;
    private javax.swing.JLabel devloperName;
    private javax.swing.JLabel name;
    private javax.swing.JLabel softName;
    private javax.swing.JLabel softNameTitle;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel toUse;
    private javax.swing.JLabel toUser;
    private javax.swing.JLabel update;
    private javax.swing.JLabel version;
    private javax.swing.JLabel versionTime;
    private javax.swing.JLabel versionTitle;
    // End of variables declaration//GEN-END:variables
}
